version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
  django:
    container_name: crud
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    # restart: always
    depends_on:
      - db

volumes:
  my-db:
