# Generated by Django 2.2 on 2020-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cedente',
            fields=[
                ('id_cedente', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('r1', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('cadastro_grupo', models.CharField(max_length=9)),
                ('cadastro', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=250)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cedente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id_fundo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fundo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoEconomico',
            fields=[
                ('id_grupo_economico', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('r1', models.IntegerField()),
                ('r2', models.IntegerField()),
                ('r3', models.IntegerField()),
                ('cadastro_grupo', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=450)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grupo_economico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LimiteCreditoCedente',
            fields=[
                ('id_limite_credito_cedente', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data_concessao', models.DateField(blank=True, null=True)),
                ('valor_nominal_limite', models.FloatField()),
                ('valor_percentual_limite', models.FloatField()),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'limite_credito_cedente',
                'managed': False,
            },
        ),
    ]
